<?php include 'views/includes/header.phtml'; ?>

<div class="row">
    <div class="col-md-6 mx-auto">
        <div class="card card-body bg-light mt-5">
            <h2>Login</h2>
            <p>Please fill in your credentials to log in</p>
            <?php if (!empty($view->error)): ?>
                <div class="alert alert-danger"><?php echo $view->error; ?></div>
            <?php endif; ?>
            <form action="login.php" method="POST">
                <div class="form-group">
                    <label for="email">Email:</label>
                    <input type="email" id="email" name="email" class="form-control" required>
                </div>
                <div class="form-group">
                    <label for="password">Password:</label>
                    <input type="password" id="password" name="password" class="form-control" required>
                </div>
                <div class="row">
                    <div class="col">
                        <button type="submit" name="login_submit" class="btn btn-success btn-block">Login</button>
                    </div>
                    <div class="col">
                        <a href="register.php" class="btn btn-light btn-block">No account? Register</a>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>

<?php include 'views/includes/footer.phtml'; ?>